version: 2.1

jobs:
  test:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - run: pip install -r db_server/requirements.txt && pytest

workflows:
  build_and_test:
    jobs:
      - test
